playground/urls.py
from django.urls import path
from . import views
app_name = "playground"

urlpatterns = [
    path("", views.index, name='index'),
    path('home/', views.home, name="home"),
    path("register/", views.registerPage, name='registration'),
    path("login/", views.loginPage, name='login'),
    path('course/', views.CoursePage, name="course"),
    path('logout/', views.logoutUser, name="logout"),
    # path("<int:post_id>/", views.post_details, name="post-detail"),
]

schoolproject/urls.py
from django.contrib import admin
from django.urls import path, include
import playground
from playground import urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(playground.urls)),
    path('__debug__/', include('debug_toolbar.urls')),

]

playground/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    GENDER_CHOICES = (
        ('F', "Female"),
        ('M', "Male"),
        ('T', "Transgender")
    )
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.EmailField(unique=True)
    age = models.IntegerField()
    date_birth = models.DateField(null=True)
    gender_choices = models.CharField(max_length=1, choices=GENDER_CHOICES, default="F")
    avatar = models.ImageField(null=True, default="avatar.svg")

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []


class School(models.Model):
    school_name = models.CharField(max_length=255)
    school_location = models.CharField(max_length=255)
    school_email = models.EmailField(unique=True)

    def __str__(self):
        return f'{self.school_name}'

    class Meta:
        ordering = ['school_name', 'school_email', 'school_location']


class Student(models.Model):
    GENDER_CHOICES = (
        ('F', "Female"),
        ('M', "Male"),
        ('T', "Transgender")
    )
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.EmailField(unique=True)
    age = models.IntegerField()
    date_birth = models.DateField(null=True)
    gender_choices = models.CharField(max_length=1, choices=GENDER_CHOICES, default="F")
    school = models.ForeignKey(School, on_delete=models.CASCADE)


class Course(models.Model):
    Course_Status = (
        ("A", "Activated"),
        ("D", "Dis-activated")
    )
    course_name = models.CharField(max_length=255)
    course_code = models.IntegerField()
    course_description = models.TextField()
    course_status = models.CharField(max_length=1, choices=Course_Status, default="D")
    school = models.ForeignKey(School, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)


class Result(models.Model):
    score = models.IntegerField()
    grade = models.CharField(max_length=5)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)


class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    body = models.TextField()
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-updated', '-created']

    def __str__(self):
        return self.body[0:50]

playground/forms.py
from django.forms import ModelForm

from playground.models import School, Student


class SchoolForm(ModelForm):
    class Meta:
        model = School
        fields = '__all__'


class MyUserCreationForm(ModelForm):
    class Meta:
        model = Student
        fields = '__all__'
        # exclude = ['school']

playground/views.py
from django.http import HttpResponse
from django.shortcuts import render

from django.contrib import messages
from django.contrib.auth import login, authenticate, logout
from django.db.models import Q
from django.shortcuts import render, redirect
from rest_framework.viewsets import ModelViewSet

from playground.forms import MyUserCreationForm, SchoolForm
from playground.models import User, School, Student, Message, Course, Result
from schoolproject.serializers import SchoolSerializers, StudentSerializers, CourseSerializers, ResultSerializers


def index(request):
    # school = School.objects.all()
    return render(request, 'school/index.html')


def registerPage(request):
    form = MyUserCreationForm()
    if request.method == 'POST':
        form = MyUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            # user.username = user.username.lower()
            user.save()
            login(request, user)
            return redirect('home')
        else:
            messages.error(request, 'An error occurred during registration')
    return render(request, 'school/registration.html', {'form': form})


def loginPage(request):
    page = 'login'
    if request.user.is_authenticated:
        return redirect('home')

    if request.method == 'POST':
        email = request.POST.get('email').lower()
        password = request.POST.get('password')

        try:
            user = User.objects.get(email=email)
        except:
            messages.error(request, 'User does not exist')

        user = authenticate(request, email=email, password=password)

        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            messages.error(request, 'Username OR password does not exit')

    context = {'page': page}
    return render(request, 'school/registration.html', context)


def logoutUser(request):
    logout(request)
    return redirect('playground:home')


def home(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ''

    schools = School.objects.filter(
        Q(school_name__icontains=q) |
        Q(school_email__icontains=q)
        # Q(__icontains=q)
    )

    students = Student.objects.all()[0:5]
    school_count = schools.count()
    school_messages = Message.objects.filter(
        Q(student__message__body__icontains=q))[0:3]
      # Q(body__name__icontains=q))[0:3]

    context = {'school': schools, 'student': students,
               'school_count': school_count, 'school_messages': school_messages}
    return render(request, 'school/home.html', context)


def CoursePage(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ''
    course = Course.objects.filter(course_name__icontains=q)
    return render(request, 'school/course.html', {'course': course})


def userProfile(request, pk):
    user = User.objects.get(id=pk)
    # rooms = user.room_set.all()
    # room_messages = user.message_set.all()
    # topics = Topic.objects.all()
    # context = {'user': user, 'rooms': rooms,
    #            'room_messages': room_messages, 'topics': topics}
    return render(request, 'school/profile.html')


class SchoolViewSet(ModelViewSet):
    queryset = School.objects.all()
    serializer_class = SchoolSerializers


class StudentViewSet(ModelViewSet):
    queryset = Student.objects.all()
    serializer_class = StudentSerializers


class CourseViewSet(ModelViewSet):
    queryset = Course.objects.all()
    serializer_class = CourseSerializers


class ResultViewSet(ModelViewSet):
    queryset = Result.objects.all()
    serializer_class = ResultSerializers


def createSchool(request):
    form = SchoolForm()
    if request.method == 'DELETE':
        form = SchoolForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('index')
        else:
            return HttpResponse("Your form is wrong")

playground/templates/school/base.html
{%load static%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    {% block css_styles %} {% endblock %}
{#<link rel="stylesheet" href="{%static 'styles.css' %}">#}
     <link rel="stylesheet" href="{%static 'style.css'%}">
<form>
</form>
</head>
<body>
    {% block content %}
    {% endblock %}

</body>
</html>

playground/templates/school/course.html
{% extends 'main.html' %}

{% block content %}
<main class="create-room layout">
  <div class="container">
    <div class="layout__box">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <a href="{% url 'playground:home' %}">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>arrow-left</title>
              <path
                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
              </path>
            </svg>
          </a>
{#          <h3>Browse Course</h3>#}
        </div>
      </div>

      <div class="topics-page layout__body">
        <form action="" method="GET" class="header__search">
          <label>
{#            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">#}
{#              <title>search</title>#}
{#              <path>#}
{#                  <a href="{% url 'playground:home' %}">#}
{#            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">#}
{#              <title>arrow-left</title>#}
{#              <path#}
{#                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">#}
{#              </path>#}
{#            </svg>#}
{#          </a>#}
{#                d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z">#}
{#              </path>#}
{#            </svg>#}
            <input name="q" placeholder="Search for course" />
          </label>
        </form>

        <ul class="topics__list">
          <li>
            <a href="{% url 'playground:course' %}" class="active">All <span>{{course.count}}</span></a>
          </li>
          {% for course in course %}
          <li>
            <a href="{% url 'playground:home' %}?q={{course.course_name}}">{{ course.course_name }} <span>{{course.school_set.all.count}}</span></a>
          </li>
          {% endfor %}

        </ul>
      </div>
    </div>
  </div>
</main>

{% endblock content%}

playground/templates/school/home.html
{#{% extends 'main.html' %}#}
{% extends 'school/base.html' %}
{% load static %}
{% block content %}

<main class="layout layout--3">
  <div class="container">

    <!-- Topics Start -->
    {% include 'school/topics_component.html' %}

  <link rel="stylesheet" href="{% static "style.css"%}">    <!-- Topics End -->

{#    <!-- Room List Start -->#}
{#    <div class="roomList">#}
{#      <div class="mobile-menu">#}
{#        <form action="{% url 'playground:home' %}" method="GET" class="header__search">#}
{#          <label>#}
{#            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">#}
{#              <title>search</title>#}
{#              <path#}
{#                d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z">#}
{#              </path>#}
{#            </svg>#}
{#            <input name="q" placeholder="Search for posts" />#}
{#          </label>#}
{#        </form>#}
{#        <div class="mobile-menuItems">#}
{#          <a class="btn btn--main btn--pill" href="{% url 'playground:course' %}">Browse Course</a>#}
{#          <a class="btn btn--main btn--pill" href="{% url 'activity' %}">Recent Activities</a>#}
{#        </div>#}
{#      </div>#}
{#           </div>#}
{#         </div>#}
{#         <label>#}
{##}
{##}
{#      <div class="roomList__header">#}
{#        <div>#}
{#          <h2>Study Rooms</h2>#}
{#          <p>{{school_count}} Schools available</p>#}
{#        </div>#}
{##}
{#        <a class="btn btn--main" href="{% url 'create-room' %}">#}
{#          <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">#}
{#            <title>add</title>#}
{#            <path#}
{#              d="M16.943 0.943h-1.885v14.115h-14.115v1.885h14.115v14.115h1.885v-14.115h14.115v-1.885h-14.115v-14.115z">#}
{#            </path>#}
{#          </svg>#}
{#          Create Room#}
{#        </a>#}
{#      </div>#}

{#      {% include 'base/feed_component.html' %}#}

    </div>
    <!-- Room List End -->

    <!-- Activities Start -->
{#    {% include 'base/activity_component.html' %}#}

    <!-- Activities End -->
  </div>
</main>

{% endblock %}

playground/templates/school/index.html
{% extends 'school/base.html' %}
{%load static%}

{% block title %}
    Index page
    {% endblock %}
    {%block css_styles %}
    <link rel="stylesheet" href="{% static "style.css"%}">
    {%endblock %}


{% block content %}
    <nav class="navbar navbar-light" style="background-color:#000080;">
        <h1 class="student " style="background-color: #4ac1f7">Student Management System <br> Welcome to Semicolon</h1>
{#    <h1 class="welcome" style="background-color: #4ac1f7">Welcome to Semicolon</h1>#}
    <a href="#" class="navbar-brand" style="background-color: skyblue;border-width:10px;border-spacing:10px;border-radius: 1px;">Login</a>
{#    <a class="navbar-link btn-lg" href="{% url 'playground:index' %}" style="background-color:#FFCC33;color:#000000;">DataFlair</a>#}
{#<a href="{% url 'admin:index' %}" class = 'navbar-link btn-lg' style="background-color:#FFCC33;color:#000000;">Admin</a>#}
{#    <a href="{% url 'upload-books' %}" class="navbar-link btn-lg" style="background-color:#FFCC33;color:#000000;">Upload Books</a>#}
</nav>
    {% endblock %}

playground/templates/school/login.html
{% extends 'school/base.html' %}

{% block content %}
<main class="auth layout">

  {% if page == 'login' %}
  <div class="container">
    <div class="layout__box">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <h5>Login</h5>
        </div>
      </div>
      <div class="layout__body">
        <h5 class="auth__tagline"></h5>

        <form class="form" action="" method="POST">
          {% csrf_token %}
          <div class="form__group form__group">
           <h1> <label for="room_name">Email</label> </h1>
            <input id="username" name="email" type="email" placeholder="e.g. ololade@email.com "/>



          <div class=" form__group">
             <label for="password">Password</label>
            <input id="password" name="password" type="password"

              placeholder="&bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;" />
          </div>

          <button class="btn btn--main" type="submit">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>lock</title>
              <path
                d="M27 12h-1v-2c0-5.514-4.486-10-10-10s-10 4.486-10 10v2h-1c-0.553 0-1 0.447-1 1v18c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-18c0-0.553-0.447-1-1-1zM8 10c0-4.411 3.589-8 8-8s8 3.589 8 8v2h-16v-2zM26 30h-20v-16h20v16z">
              </path>
              <path
                d="M15 21.694v4.306h2v-4.306c0.587-0.348 1-0.961 1-1.694 0-1.105-0.895-2-2-2s-2 0.895-2 2c0 0.732 0.413 1.345 1 1.694z">
              </path>
            </svg>

            Login
          </button>
        </form>

        <div class="auth__action">
          <p>Haven't signed up yet?</p>
          <a href="{% url 'playground:registration' %}" class="btn btn--link">Sign Up</a>
        </div>
      </div>
    </div>
  </div>
  {% else %}
  <div class="container">
    <div class="layout__box">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <h3>Register</h3>
        </div>
      </div>
      <div class="layout__body">
        <h2 class="auth__tagline">Find your study partner</h2>

        <form class="form" action="" method="POST">
          {% csrf_token %}

          {% for field in form %}
          <div class="form__group form__group">
            <label for="room_name">{{field.label}}</label>
            {{field}}
          </div>
          {% endfor %}


          <button class="btn btn--main" type="submit">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>lock</title>
              <path
                d="M27 12h-1v-2c0-5.514-4.486-10-10-10s-10 4.486-10 10v2h-1c-0.553 0-1 0.447-1 1v18c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-18c0-0.553-0.447-1-1-1zM8 10c0-4.411 3.589-8 8-8s8 3.589 8 8v2h-16v-2zM26 30h-20v-16h20v16z">
              </path>
              <path
                d="M15 21.694v4.306h2v-4.306c0.587-0.348 1-0.961 1-1.694 0-1.105-0.895-2-2-2s-2 0.895-2 2c0 0.732 0.413 1.345 1 1.694z">
              </path>
            </svg>

            Register
          </button>
        </form>

        <div class="auth__action">
          <p>Already signed up yet?</p>
          <a href="{% url 'login' %}" class="btn btn--link">Sign Up</a>
        </div>
      </div>
    </div>
  </div>
  {% endif %}
</main>
{% endblock content %}

playground/templates/school/registration.html
{% extends 'school/base.html' %}
{% load static %}
{% block content %}
    <h5>REGISTRATION</h5>
    {% block title %}

    {% endblock %}
    {%block css_styles %}
    <link rel="stylesheet" href="{% static "style.css"%}">
    {%endblock %}

{% if page == 'login' %}
<div>
    <form method="POST" action="">
        {% csrf_token %}
{#            <a href="#" class="navbar-brand" style="background-color: skyblue;border-width:10px;border-spacing:10px;border-radius: 1px;">Login</a>#}
        <label>Username:</label>
        <input type="text" name="username" placeholder="Enter Username" />
        <br>
        <br>
         <label>Password:</label>

         <div class="Ololade">password must contain letters, numbers and symbol</div>

        <input type="password" name="password" placeholder="Enter Password" />

        <input type="submit" value="Login" />
    </form>

    <p>havent signed up yet?</p>
    <a href="{% url 'playground:registration' %}">Sign up</a>
</div>

{% else %}

<div>
    <form method="POST" action="">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Register" />
    </form>
    <p>Already signed up yet?</p>
    <a href="{% url 'playground:login' %}">Login</a>
</div>
{% endif %}

{% endblock content %}

playground/templates/school/school_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>School</title>
</head>
<body>
<h1>School Detail Page</h1>
<h2>{{school.name}}</h2>
<h2>{{school.email}}</h2>
<h2>{{school.location}}</h2>

</body>
</html>

playground/templates/school/topics_component.html
<div class="topics">
    <div class="topics__header">
        <h2>WELCOME TO OLOLADE'S STUDY ROOM...
            <br>
            <br>
            <link href="", >

          <br> Browse Topic
        </h2>
    </div>
    <ul class="topics__list">
        <li>
            <a href="{% url 'playground:home' %}" class="active">All <span>{{topics.count}}</span></a>
        </li>
        {% for course in topics %}
        <li>
            <a href="{% url 'playground:home' %}?q={{course.name}}">{{course.name}}<span>{{course.room_set.all.count}}</span></a>
        </li>
        {% endfor %}

    </ul>
    <a class="btn btn--link" href="{% url 'playground:course' %}">
        More
        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
            <title>chevron-down</title>
            <path d="M16 21l-13-13h-3l16 16 16-16h-3l-13 13z"></path>
        </svg>
    </a>
</div>